<a href="https://colab.research.google.com/github/Jiya-786/Statistics_notes/blob/main/TUT/TUT-2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
#creating arrays in numpy
py_list=[1,2,3,4,5]
arr=np.array(py_list)

print("Python list: ",py_list)
print("Numpy array: ",arr)
print("Shape of array: ",arr.shape)

#creating a 2D array
matrix=np.array([[1,2,3],[4,5,6]])
print("2D matrix\n: ",matrix);
print("Matrix shape: ",matrix.shape)



Python list:  [1, 2, 3, 4, 5]
Numpy array:  [1 2 3 4 5]
Shape of array:  (5,)
2D matrix
:  [[1 2 3]
 [4 5 6]]
Matrix shape:  (2, 3)


In [4]:
#slicing and indexing in numpy
matrix=np.array([10,20,30,40])
print(matrix[0])
print(matrix[-1])
print(matrix[1:4])

10
40
[20 30 40]


In [5]:
#slicing and indexing in 2D array
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix[0,1]) #row 0 column 1
print(matrix[:,1]) #all rows column 1

2
[2 5]


In [6]:
#data type in numpy
matrix1=np.array([1,2,3])
print(matrix1.dtype)

matrix2=np.array([1,2,3],dtype=float)
print(matrix2.dtype)


int64
float64


In [7]:
#shape vs size vs ndim
""" shape -> structure
    size -> tot no.of elts
    dim -> no.of dimensions """

matrix=np.arange(12)
print("og matrix: ",matrix)
matrix=matrix.reshape(3,4)
print("rearranged matrix: \n",matrix)
print("Shape: ",matrix.shape)
print("Size: ",matrix.size)
print("Dimension: ",matrix.ndim)   # here we have row,column hence dimension is 2.
                                   # going further we can also find another 3rd dimension
                                   # other than row and column although the matrix can be hard to imagine



og matrix:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
rearranged matrix: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape:  (3, 4)
Size:  12
Dimension:  2


In [8]:
# 3x3x3 matrix ie 3 dimensions matrix, one extra dimension other than row and column
matrix=np.arange(1,28).reshape(3,3,3)
print(matrix)
print("Required elt: ",matrix[0,2,1])    #indexing of rows and columns also starts from 0


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Required elt:  8


In [9]:
# 4x4x4 matrix
matrix=np.arange(1,82).reshape(3,3,3,3)
print(matrix)

print("Required elt: ",matrix[0,2,2,1])     #open from outside bracket to inside bracket

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]]

  [[46 47 48]
   [49 50 51]
   [52 53 54]]]


 [[[55 56 57]
   [58 59 60]
   [61 62 63]]

  [[64 65 66]
   [67 68 69]
   [70 71 72]]

  [[73 74 75]
   [76 77 78]
   [79 80 81]]]]
Required elt:  26


In [10]:
# extra functions
# Creates a 2×3 array filled with zeros
zeros_arr = np.zeros((2, 3))
print("Zeros Array:\n", zeros_arr)

# Creates a 3×3 array filled with ones
ones_arr = np.ones((3, 3))
print("\nOnes Array:\n", ones_arr)

# Creates a 3×3 identity matrix
identity_arr = np.eye(3)
print("\nIdentity Matrix:\n", identity_arr)

# Generates 5 evenly spaced numbers between 0 and 1 (inclusive)
linspace_arr = np.linspace(0, 1, 5)
print("\nLinspace Array:\n", linspace_arr)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Linspace Array:
 [0.   0.25 0.5  0.75 1.  ]


In [11]:
# Mini-Exercise 1
# Create a NumPy array of numbers from 0 to 9 using np.arange(10).
# Reshape it into a 2x5 matrix using .reshape().
# Calculate the sum of all elements.

ar=np.arange(10).reshape(2,5)
tot_sum=np.sum(ar)

print(tot_sum)

45
